name: Trigger website update

on:
  release:
    types: [published]

jobs:
  trigger-website-update:
    name: Trigger website update
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@v1.2.2
      with:
        workflow: build.yml
        repo: xemu-project/xemu-website
        token: ${{ secrets.XEMU_ROBOT_TOKEN }}
        ref: master
